version: '3'

services:
  home:
    build:
      context: ./home
      dockerfile: ./Dockerfile
    container_name: home
    volumes:
      - ./home:/app
    ports:
      - "5001:5001"
    networks:
      - 5bility

  user:
    build:
      context: ./user
      dockerfile: ./Dockerfile
    container_name: user
    volumes:
      - ./user:/app
    ports:
      - "5002:5002"
    networks:
      - 5bility

  list:
    build:
      context: ./list
      dockerfile: ./Dockerfile
    container_name: list
    volumes:
      - ./list:/app
    ports:
      - "5003:5003"
    networks:
      - 5bility

  evaluation:
    build:
      context: ./evaluation
      dockerfile: ./Dockerfile
    container_name: evaluation
    volumes:
      - ./evaluation:/app
    ports:
      - "5004:5004"
    networks:
      - 5bility

  community:
    build:
      context: ./community
      dockerfile: ./Dockerfile
    container_name: community
    volumes:
      - ./community:/app
    ports:
      - "5005:5005"
    networks:
      - 5bility

  grade:
    build:
      context: ./grade
      dockerfile: ./Dockerfile
    container_name: grade
    volumes:
      - ./grade:/app
    ports:
      - "5006:5006"
    networks:
      - 5bility

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: ct_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ct1234
      MYSQL_DATABASE: classtime
    networks:
      - 5bility

networks:
  5bility:
    external: true
